apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlife-vault-pvc
  namespace: gitlife
  labels:
    app: gitlife
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: fast-ssd  # Adjust based on your cluster